### ISSUE TITLE
[Bug] Sys-DVR starts on boot

### ISSUE THREAD

**Issue by Goginha** [exelix11/SysDVR#119]

**Comment by Goginha** [comment]
I have to turn it off every time I turn on my switch, because then some games wont run.

**Comment by exelix11** [comment]
> because then some games wont run

I'm not sure what you mean with this, as far as i know all games work fine with sysdvr running. 

> I have to turn it off every time 

Again you seem to be confused, how do you "turn it off" ? Using the settings app ? that doesn't close sysdvr it just stops waiting for a client so i don't think that's the solution to your issue.
Either way after you disable streaming you can press on "Set current as default mode on boot" and sysdvr will not stream on boot.
Still that won't prevent auto launch on boot as that's how sysmodules are supposed to work.

I feel like there's some other problem with your cfw setup.

**Comment by Goginha** [comment]
Okay, I dont think I explained well, Every time I boot up my switch, Sys-dvr starts streaming, and some games don't work with streaming (like smash ultimate) I put sys-dvr to not stream when I boot up my switch, but even then it starts streaming, and smash ultimate gives an error until I open sys-dvr and then click on stop streaming, then it works. I have to do this every time I boot up my switch and it gets annoying.

**Comment by exelix11** [comment]
As i said if you press on "set the current mode as default on boot" after you pressed stop streaming it will not stream on boot.

If that doesn't work deleting /config/sysdvr from your sd card should do the trick.

The problem is that i don't think sysdvr is causing the error you mentioned because when there's no pc connected sysdvr won't do anything at all and regardless of that games that are not compatible like smash bros don't initialize recording at all so they shouldn't be affected.

I believe you may have some other mod or sysmodule causing this issue.

**Comment by Goginha** [comment]
Deleting /config/sysdvr didn't fix it, and my only sysmodules are sys ftpd, saltynx, emuiibo, and sysDVR

**Comment by ELY3M** [comment]
Can you remove saltynx?      that sysmodule caused too many issues....

**Comment by Goginha** [comment]
> Can you remove saltynx? that sysmodule caused too many issues....

Just uninstalled it and know it is fixed,
