### ISSUE TITLE
[Bug] Asserition failed: pointer is null Could not initialize EGL

### ISSUE THREAD

**Issue by potatoxbe** [exelix11/SysDVR#128]
**Describe the bug**
Testing this on Raspberry Pi OS 32bit and 64bit on Pi 3B+ and Pi 4.

Pi 3 works fine when I'm using Legacy drivers on 32bit, though laggy and unplayable. But got the following error when I'm using GL drivers Full KMS and Fake KMS on both Pi 3 and 4 in Raspberry Pi OS 32 and 64 bit. 

```
 System.Exception: Asserition failed: pointer is null Could not initialize EGL
    at SysDVR.Client.Player.Exten.Assert(IntPtr val, Func`1 MessageFun)
    at SysDVR.Client.Player.Player.InitSDLVideo(String scaleQuality)
    at SysDVR.Client.Player.Player.UiThreadMain()
    at SysDVR.Client.Player.PlayerManager.MainThread()
    at SysDVR.Client.Program.StartStreaming(BaseStreamManager streams)
    at SysDVR.Client.Program.InnerMain(String[] args)
    at SysDVR.Client.Program.Main(String[] args)
```

**To Reproduce**
Followed your guide installing following packages `ffmpeg libsdl2-dev libusb-1.0-0`. Only manually installing dotnet works for me properly to launch dotnet. Even tried to compile my own SDL from here https://github.com/midwan/amiberry/wiki/Compile-SDL2-for-KMSDRM, since reading around it seems an issue with KMS drivers (which only Pi4 has), does not seem to support Dispmanx and to use X. But I'm a Linux noob. 

Works perfectly on my PC and is awesome to use. Would be amazing to get this working on a small device. 

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Setup information**
 - PC Os: Raspberry Pi OS 32bit, 64bit on Raspberry Pi 3B+ and Raspberry Pi 4B
 - Nintendo firmware 10.2.0
 - SXOS 3.1.0
 - SysDVR 5.1

**Additional context**
[Add any other context about the problem here.]

**Comment by exelix11** [comment]
Unfortunately i don't have a pi 4 and i'm not interested in getting one just for this.
I implemented the client with arm support so i'm not actively preventing people from using it on arm devices but there isn't much more i can do.

I'm not into linux dev either so i can just give you some general troubleshooting advice:
- Make sure you built SDL for the same architecture as the dotnet you're using (arm32 vs arm64), same for ffmpeg
- Make sure sysdvr-client is actually picking up your custom SDL.so instead of the system installed one. (check with LD_DEBUG)
- Look into SDL environment variables to override its default rendering, maybe you can just avoid using EGL altogether

That's all i can think of rn, will leave this open in case someone else can figure it out.

**Comment by potatoxbe** [comment]
``

**Comment by potatoxbe** [comment]
```
Make sure sysdvr-client is actually picking up your custom SDL.so instead of the system installed one. (check with LD_DEBUG)
```

Yes that's it. Didn't realize its still picking up the old directory. Totally works now on Pi 4, though there's an occasional stutter every 10 secs. I'm sure figuring out hardware accelerated decoder on this thing should smooth things out.

**Comment by potatoxbe** [comment]
After testing, the stutter is actually when it's in USB mode. Looks to be an issue with Pi. Using TCP works flawlessly, just like PC. You can close this now.
