### ISSUE TITLE
[Bug] Collection of mana picture corruption

### ISSUE THREAD

**Issue by cybercuate** [exelix11/SysDVR#129]
**Describe the bug**
Collection of mana picture corruption

**To Reproduce**
open Collection of mana, sit and watch how the picture corrupts itself

**Expected behavior**
work fine

**Setup information**
 - PC Os:  Windows 10 x64
 - Console firmware 11.0.1
 - Custom firmware name and version Atmosphere M.17.1
 - SysDVR version 5.1 USB

**Additional context**
After pressing A and just leaving the menu in Mystic Quest picture doesn't corrupt. Wierd, huh?
![Captura de pantalla 2021-04-12 170754](https://user-images.githubusercontent.com/46688955/114463137-0aa4f980-9bb2-11eb-9bfb-d5101ac46035.jpg)
![Captura de pantalla 2021-04-12 170535](https://user-images.githubusercontent.com/46688955/114463169-155f8e80-9bb2-11eb-9912-86bec18752a5.jpg)
![Captura de pantalla 2021-04-12 171130](https://user-images.githubusercontent.com/46688955/114463223-24ded780-9bb2-11eb-82d0-ae2ef6ab44de.jpg)

**Comment by exelix11** [comment]
Unfortunately i don't have the game, will post a test build tomorrow so you can test if this is the same issue as the one that last update should have fixed.

In the meantime, are you sure you updated to the latest version both the pc client and the sysdvr sysmodule on your switch ?

**Comment by exelix11** [comment]
Was looking through old issues and found this one i completely forgot about. Are you still experiencing this ?
Will keep this opened for now in case of more reports.

**Comment by cybercuate** [comment]
> 
> 
> Was looking through old issues and found this one i completely forgot about. Are you still experiencing this ?
> Will keep this opened for now in case of more reports.

Yes, the problem still exists. Is there a chance you can check it?

**Comment by exelix11** [comment]
I don't have the game, can you try streaming with this [build](https://github.com/exelix11/SysDVR/files/6821970/atmosphere.zip) ?
If this is the same bug as #91 it will crash with error code 0x2269 instead of showing glitches.

**Comment by cybercuate** [comment]
> 
> 
> I don't have the game, can you try streaming with this [build](https://github.com/exelix11/SysDVR/files/6821970/atmosphere.zip) ?
> If this is the same bug as #91 it will crash with error code 0x2269 instead of showing glitches.

Nope, it is actually worst. It goes into a 1 fps mode or something (in the PC client) so it glitches very slowly and gets as corrupted as always. So, the problem is still the same. I updated to 12.1 and ATM 19.5 and the problem is the same.

**Comment by exelix11** [comment]
This is weird. I've prepared another build with more logging: 
[sysmodule](https://github.com/exelix11/SysDVR/files/6829933/atmosphere.zip) and [client](https://mega.nz/file/Ach2kYrL#frEegdwzamcYu2MTc41hARGR5dZczVB3eKtDwKAUU78) (had to upload on mega cause it's too big for github).

While streaming with this it will log the kind of packets it receives from the console, here's an example of a good stream:

`{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{7 8 5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{7 8 5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{7 8 5 }`

This kind of glitch usually happens when packets of kind 5 are missing, can you paste here a few lines of the output ? Worth mentioning they should appear continuously, if you see a few seconds between a digit and another it means there's some kind of delay in the recording output.

Also i've enabled strict error checking on video recording so if you console crashes post the error code.

**Comment by cybercuate** [comment]
> 
> 
> This is weird. I've prepared another build with more logging:
> [sysmodule](https://github.com/exelix11/SysDVR/files/6829933/atmosphere.zip) and [client](https://mega.nz/file/Ach2kYrL#frEegdwzamcYu2MTc41hARGR5dZczVB3eKtDwKAUU78) (had to upload on mega cause it's too big for github).
> 
> While streaming with this it will log the kind of packets it receives from the console, here's an example of a good stream:
> 
> `{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{7 8 5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{7 8 5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{5 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{1 }{7 8 5 }`
> 
> This kind of glitch usually happens when packets of kind 5 are missing, can you paste here a few lines of the output ? Worth mentioning they should appear continuously, if you see a few seconds between a digit and another it means there's some kind of delay in the recording output.
> 
> Also i've enabled strict error checking on video recording so if you console crashes post the error code.

Hey, >>this build<< works well. I got a video of it. Some quality is still lost but maybe it is because of the compression and I get that. Check it and tell me what do you see in those numbers.
[https://streamable.com/obk5oj](url)

**Comment by cybercuate** [comment]
Ok, I decided to fromat my SD card, delete all of the clients in my PC and redownload SysDVR 5.1 again to make an everything clean install and it just works now. Checking it closer, I was using a combination of 5.0.2 PC client and the 5.1 nro (how that happened?). You can close this issue now, I will be more careful from now on.
