### ISSUE TITLE
[Feature request] Audio for very low latency mpv video streams

### ISSUE THREAD

**Issue by Yuuzername** [exelix11/SysDVR#139]
**Is your feature request related to a problem? Please describe.**
Suggesting an improvement for reduce the latency of the video and audio streams together from the [recommended low latency settings](https://github.com/exelix11/SysDVR/wiki/Low-latency-streaming#video-and-audio-low-latency). While a [very low latency solution](https://github.com/exelix11/SysDVR/wiki/Low-latency-streaming#video-very-low-latency) already exists, the compromise with using it is that only a single channel can be streamed.

**Describe the solution you'd like**
A combination of the very low latency video stream from mpv plus the audio from the Switch which is connected via audio jack (as a line in source) may improve this.

You can _kinda_ already do this on Windows by starting a low latency mpv video stream, then going into sound settings in the control panel, recording tab, selecting whichever device is the line in for the Switch (mine was "Jack Mic")>listen tab and ticking the listen to this device option. However, it isn't great for streaming on places like Discord or Parsec where users can only hear the audio from the focused window.

This may be resolved by combining the low latency mpv video stream with the line-in audio jack stream to play in one window.

**Comment by exelix11** [comment]
From the same page you linked 
> Since version 5.0 SysDVR-Client will stream with its built-in player in low latency mode by default. The steps explained here are only for RTSP or stdin interfaces to stream to other players.

The rtsp and stdin options are still there for compatibility with other players and were used before version 5.0. 
The built-in player already has the lowest possible latency and solves the discord screenshare audio problem so i'm not interested in keeping on working on the other modes.

Besides, microphones on audio jacks only have one audio channel so you would lose stereo sound. And because of cross platform support i'm not going to add windows specific features such as modifying audio settings.
