### ISSUE TITLE
[Feature request] Delay for streaming with better quality

### ISSUE THREAD

**Issue by phiwi05** [exelix11/SysDVR#177]
So I like to stream my game to my PC for having audio from the game and streaming to my friends on discord while having my switch connected to my monitor with the dock. This works great but when I stream the window to them, so they can watch me play, it does not work as well, because of the low resolution and sometimes visual glitches.

My solutions would be to somehow make it possible to stream the switch to the PC via some cable in docked mode which I don't know if it's even possible.

My second and more likely solution would be to make the program able to have some setting to st a delay so that it has more time to comprehend the streamed content. This would result in better quality in cost of more delay which isn't that important when you play on a monitor.

If you or someone could program this, it would be an awesome and free alternative for a capture card for streaming on discord or even twitch.

**Comment by exelix11** [comment]
Did you try the RTSP modes with vlc or mpv ? Those should properly implement buffering and show less glitches but with a few seconds of delay.
Actually i don't remember how well do they work cause haven't used them in a while but in theory should fit your use case.

**Comment by phiwi05** [comment]
> Did you try the RTSP modes with vlc or mpv ? Those should properly implement buffering and show less glitches but with a few seconds of delay. Actually i don't remember how well do they work cause haven't used them in a while but in theory should fit your use case.

I tried but didn't get it to work... if you know a tutorial, let me know pls.
But implementing this into the standard sysdvr client would be a great idea too!

**Comment by exelix11** [comment]
Implementing proper buffering from scratch is quite some work and not really something i'm planning to do.

To use RTSP there are two ways: [Simple network mode](https://github.com/exelix11/SysDVR/wiki/Network-RTSP-mode-(default-mode)) and [TCP Bridge](https://github.com/exelix11/SysDVR/wiki/Network-TCP-Bridge-mode) but instead of using the built-in player you pick to [relay over RTSP](https://github.com/exelix11/SysDVR/wiki/Advanced-tips#streaming-with-different-players)
