### ISSUE TITLE
[Feature request] Streaming directly to YouTube, Twitch, etc

### ISSUE THREAD

**Issue by DamianArielLerner** [exelix11/SysDVR#210]
I would love to stream directly to YouTube instead of sending the video to my PC, then to obs and then to the streaming platform. I don't know if it's possible to send the video directly to the servers but I would appreciate it so much. Just imagine saving all your gameplays in YouTube without using a PC and watching it in any moment you want.

**Comment by exelix11** [comment]
I did look into this once, the main issue is youtube/twitch not supporting the exact encoding switch uses. 
If i remember correctly they require the soruce to send a keyframe at least every two seconds while the switch encoder is variable.
I don't know if there's a workaround for that but even if there was there could be memory related issues since i'd also need to implement API clients for those platforms and that will most likely require increasing sysdvr's memory usage (which i managed to never increase since the first release).

In practice i don't think it's impossible but definitely not something i'm interested in, PR are welcome i guess even though i think this kind of feature may requires a fork that does just web streaming.
