### ISSUE TITLE
Internet streaming not working [Bug] 

### ISSUE THREAD

**Issue by Rei-rahul** [exelix11/SysDVR#215]
**Describe the bug**
[Usb streaming using SYSDVR works fine but when I try using tcp or ip streaming "Invalid source" appears, any idea why this happens?.]

**To Reproduce**
[using the TCP or RTSP modes]

**Expected behavior**
[streaming over internet working?]

**Setup information**
 - PC Os: Mac OS 12.3
 - Console firmware: latest version
 - Custom firmware:  latest version
 - SysDVR version: latest version

**Additional context**
[Thank you]

**Comment by exelix11** [comment]
Invalid source means your command line is wrong. 

For TCP bridge you need to run sysdvr client like `dotnet SysDVR-Client.dll bridge IP_ADDRESS`, for example `dotnet SysDVR-Client.dll bridge 192.168.1.24`

For "Simple networ" mode you don't need sysdvr client since that's a regular RTSP stream, you can just type in VLC the ip and port shown in sysdvr settings as `rtsp://IP_ADDRESS:6666/` so with the same example IP as before it would be `rtsp://192.168.1.24:6666/`

**Comment by Rei-rahul** [comment]
-Yup I forget to type in "bridge" 
-I've tried it with Lan play custom IP and its not working I guess I need to shut off that in order for this to work.
-Simple network kinda slow with noticeable input delay
One more thing how to tell terminal that SysDVR-Client.dll exist without revering to its original folder everytime? do you know?

**Comment by Rei-rahul** [comment]
> You can make a script file that will run the command from the proper directory and make a shortcut to it on your desktop, can't give you the exact steps for mac os but it should be possible.

I think I got it working using Automator

 > It's possible but not recommended [spacemeowx2/switch-lan-play#83](https://github.com/spacemeowx2/switch-lan-play/issues/83) 

 "btw it is dangerous to expose the port when using switch-lan-play. Anyone on the same server can access Switch's port 6666." maybe that's why its not recommended. 
Yet I have no idea how to add a second IP on mac
Is it "DHCP with manual address" ?

**Comment by exelix11** [comment]
Unfortunately i don't know.

**Comment by Rei-rahul** [comment]
No problem, I just made a comment on that post.
Thank you :)
