### ISSUE TITLE
[Bug] Bad quality with kefir>660

### ISSUE THREAD

**Issue by gruntikFor** [exelix11/SysDVR#219]
After updating kefir to version 660 and higher, the picture quality via USB became worse.
Please add support for the latest version of kefir.

**Comment by exelix11** [comment]
I never heard of thi kefir thing, how does it releate to SysDVR ?
Are you sure whatever you're talking about is not a coincidence ?

**Comment by exelix11** [comment]
From the backstage i've been informed that it's a cfw pack (and its host seems to be down atm)
These AIO packs often redistriute OSS software without respecting licenses or are just piracy oriented.
I'm not providing support for them as i don't even know which version of SysDVR its redestributing (assuming it does, didn't check).

Since at their core these packs all run Atmosphere try downloading latest version of SysDVR from the official [releases page](https://github.com/exelix11/SysDVR/releases) and try again. If the issue persists i don't know how to help you since sSysDVR didn't receive any changes since December which means any issue is likely in your setup (bad cables, driver issues, overlock and so on)
