### ISSUE TITLE
[Bug] cannot connect network with v6.0.0

### ISSUE THREAD

**Issue by xqbumu** [exelix11/SysDVR#256]
**Describe the bug**
When I installed version v6.0.0, I encountered a network error with error code 2162-0002. However, after I deleted the installation files, the network connection was normal.

**To Reproduce**
Even after uninstalling and reinstalling the software, I can still encounter this error.

**Setup information** 
 - PC Os: MacOS 14.1.2 (23B92)
 - Console firmware 17.0.0
 - Custom firmware name and version Atmosphere 1.6.2
 - SysDVR version 6.0.0 SysDVR.zip

**Additional context**

I have already cleaned up the hidden files use `find . -type f -name '._*' | xargs rm` and `find . -type f -name '.DS_Store' | xargs rm`.

Version v5.5.6 can connect to the internet normally.

**Comment by exelix11** [comment]
Switchbrew reprorts 2162-0002 as
> Can be triggered by running svcBreak. The svcBreak params have no affect on the value of the thrown error-code.

Are you sure this is the error code you get ? Where do you get it exactly ?

Try again but with the USB only version of sysdvr, does the same happen ?

**Comment by xqbumu** [comment]
Everything returned to normal after I deleted the installation files. So, I guess something maybe wrong after I installed SysDVR.

USB Model is ok with USB only version AND Or SysDVR.zip version.

I also got error code: 2123-0011 when I removed my network connection's proxy settings, but I don't know what has changed.

**Comment by exelix11** [comment]
When you get these errors do you mean the console completely crashes with a fatal screen ? If so can you read the title ID that causes the crash ?

The only major difference in the v6 sysmodule is the lan discovery feature, try disabling it by creating an empty file on your sd card called `/config/sysdvr/no_adv` (if you are on windows mind that the file has no extension, also create the folders that don't exist), then reboot.

If this does not fix it i think it may be a memory issue, you should try sysdvr on a clean install of atmosphere to make sure it's not something caused by the interaction of multiple sysmodules.

**Comment by xqbumu** [comment]
I use [atmosphere-1.6.2-master-f7bf379cf+hbl-2.4.4+hbmenu-3.6.0.zip](https://github.com/Atmosphere-NX/Atmosphere/releases/download/1.6.2/atmosphere-1.6.2-master-f7bf379cf+hbl-2.4.4+hbmenu-3.6.0.zip) with SysDVR v6.0.0 and patched with /config/sysdvr/no_adv, the error code 2123-0011 occured again, the detail is:

Error Code: 2123-0011 (0x167b)
Program: 0100000000000025
Firmware: 17.0.0 (Atmosphère 1.6.2-master-f7bf379cf)
<img width="1133" alt="image" src="https://github.com/exelix11/SysDVR/assets/6274534/19335bba-641e-4dbf-bda0-a99480d31134">

**Comment by exelix11** [comment]
Just to confirm, did you reboot after creating the no_adv file ?

Unfortunately i don't have an explaination for this behavior, i suggest getting a second sd card and setting it up from scratch with just atmosphere and sysdvr to evaluate in isolation if the crash is caused by it or it is some combination of factors (multiple mods, sd corruption, out of memory, etc)

**Comment by xqbumu** [comment]
Yes, I have shutdown and reboot after after creating the no_adv file.

**Comment by 1332348216** [comment]
Can kindly request the author to open the external language text of sysdvr？so that everyone can easily convert to their familiar language.

**Comment by exelix11** [comment]
> Can kindly request the author to open the external language text of sysdvr？so that everyone can easily convert to their familiar language.

I did look into it but getting proper font support for the various alphabets was taking up too much time, may plan it for the next release.

**Comment by 1332348216** [comment]
thanks you
