### ISSUE TITLE
 [Feature request]  Xbox version client

### ISSUE THREAD

**Issue by mustafapx** [exelix11/SysDVR#276]
Is it possible to compile a version for the xbox one / series that can be installed with dev mode? It would be awesome and a quick way to play on tv without using a pc or an android tv box

**Comment by exelix11** [comment]
Probably not as-is, i think the whole thing would have to be repackaged as a UWP app.
From a quick search it seems all the major sysdvr-client native components are supported on xbox so porting it may be possible.  Not sure about USB support since that requires the google drivers.
However i don't have an xbox and i'm not currentrly interested in making the port.

If others are interested feel free to discuss here, in the meantime i'll close the issue.
