### ISSUE TITLE
[Feature request] support for `armeabi-v7a`

### ISSUE THREAD

**Issue by laralove143** [exelix11/SysDVR#291]
**Is your feature request related to a problem? Please describe.**
im trying to install this on my android tv which has the `armeabi-v7a` architecture, apparently the provided apk doesnt support this because im getting this error:
```
$ adb install SysDVR-Client-Android-arm64.apk
Performing Streamed Install
adb: failed to install SysDVR-Client-Android-arm64.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Describe the solution you'd like**
a prebuilt library with support for `armeabi-v7a`, or at least compilation guide that explains how to do this

**Describe alternatives you've considered**
building it from source myself, i actually went head-on into this and it was not fun, ndk and cmake are not fun

**Additional context**
this is a common architecture found in android tvs, which is a great use-case of this app imo

**Comment by exelix11** [comment]
That is not possible because the android app is a direct port of the pc client, which uses dotnet aot and some hacks to build for android. Dotnet aot currently only supports 64bit arm.

32bit android support would require either a native client written from scratch or some more hacks to get non aot version of dotnet to run in an apk.

I'm currently not interested in either, that's why currently this is not planned.
