### ISSUE TITLE
[Feature request]  iOS IPA SysDVR Client

### ISSUE THREAD

**Issue by Ixolaro** [exelix11/SysDVR#299]
I would like a client version for iOS in .ipa application package
because its annoying to use VLC with delay on iPhone

**Comment by exelix11** [comment]
Last i checked libusb was not compatible with ios so an iPhone port would be limited in that regard, aside from that it's probably possible.

However, I don't have any apple device  so I can't do development for those platforms.

**Comment by Ixolaro** [comment]
well MacOS has virtual iPhones, so if you hackintosh your pc or one of them couldn't you do development? or do you have a mac?

**Comment by exelix11** [comment]
I don't have a mac either. Last time i tried an hackintosh setup for mac os support it was a terrible and laggy experience. I will not bother doing dev without real hardware.
Mac OS is supported solely because it comes out of the box with dotnet so the mainteinance effort is minimal, i expect ios to be like android where i have to do countless hacks to package a native compiled binary in a shell app.

**Comment by Ixolaro** [comment]
i have a non-laggy hackintosh with dev tools installed so i could give you remote acces to it

**Comment by exelix11** [comment]
That sounds inconvenient as hell for the both of us.
If you or anyone else wants to work on a port I'm all for it and I can answer technical questions.
As for me I'll not be buying 2k+ of equipment just for sysdvr, besides I find macos incredibly annoying to use.

**Comment by NsCrosu** [comment]
Can sysdvr be modified as a "virtual USB camera" mode so that we won't need a new ipa. Just like what a Capture Card do? Then we can just use apps like Monicon on iPad or OBS on PC.

**Comment by exelix11** [comment]
I tried that at some point but i couldn't manage it due to how the switch os usb api works, I'm not sure it's possible.

**Comment by oppalla** [comment]
@exelix11 , please, I really badly need a way to connect sysdvr with my ipad. I work and live onboard ships, and the only screen I have bigger than my switch in my cabin is my iPad. I can easily install any ipa on it due its having TrollStore installed. 

If you cannot develop an ipa client for iOS, by any chance, is there any other app that may accept the connection from the switch?

With VLC it works beautifully but, the latency makes it impossible to play. 

As suggested by @NsCrosu if it was possible to be recognised as a USB camera, after iOS 17 it would have native support on iPads and iPhones.

If you need any assistance to develop this questions, ill be 100% available for you.

Thank you so much

**Comment by exelix11** [comment]
As i said, i lack the hardware to make a proper ios port and i'm not spending a considerable amount of money on devices i don't have an use for just for an hobby project.

Usb video mode is not a thing because as of last time i tried the switch OS lacked proper api to implement it.

Your current best bet is to try various video players that support RTSP until you find one that allows reducing buffering so you get less latency, stuff like IP cam monitoring software and so on.

I'll study the possibility of an apple devices port whenever i happen to actually need a mac and end up geting one.

**Comment by oppalla** [comment]
Unfortunately using wireless streaming its not an option, even because it frequently lags and freezes the switch, leading to force reboot sometimes.

I wish I could help you to purchase an Apple device to develop a simple app for it.

My next try will be virtualization of Linux or windows on the ipad through UTM, just to install this USB driver and the sysdvr client to check if it becomes playable. 

As soon as I have tested it I’ll come back here to leave an answer for the next coming iOS users that may benefit for it.

For now, I recommend to newcomers the PSVita which works flawlessly, connected with only one cable to iPad and running on FaceTime app.

**Comment by exelix11** [comment]
> Unfortunately using wireless streaming its not an option, even because it frequently lags and freezes the switch, leading to force reboot sometimes.

You can try a physical network switch and plugging both the ipad and the console with a lan adapter. On windows sometimes that works more reliably than USB.

> My next try will be virtualization of Linux or windows on the ipad through UTM, just to install this USB driver and the sysdvr client to check if it becomes playable.

I feel like virtualization will not work well due to the overhead of arm to x86 translation, that is assuming you get USB to work at all. If you plan on using native windows for arm don't bother as currently that is not supported either. I do plan on getting a windows on arm device to implement it eventually.

**Comment by oppalla** [comment]
Unfortunately the physical network switch and the wifi options are not available because, where I live i can’t use my own modem, since the network here don’t allow it. Also for the small space, there is no room for much cabling. The one cable, putting the switch beside the ipad is the best scenario.
Another option will maybe be the purchase of an old android tablet with big screen just for this use, but as well, in the tiny space it will become more of a hassle. 
Anyway, we can always wait for the good will of a iOS dev to translate your client to the iOS language… so I’m going to hope for it.
anyway, thanks for supporting and for developing this awesome tool!

**Comment by exelix11** [comment]
Other developers can make their own clients just fine, the protocol is documented in the readme files around the repo.
