### ISSUE TITLE
[Help] Bluetooth audio directly to PC?

### ISSUE THREAD

**Issue by ImportTaste** [exelix11/SysDVR#57]
Reading the new patch notes, it sounds like the low-latency streaming option is even faster than USB streaming because it can stream just a single channel for higher bandwidth and it can take advantage of overclocking through ReverseNX (since the console being flagged as undocked imposes limits on clock speed).

But that does mean the gameplay would be silent, so that makes me wonder if there is a way to connect the audio to the PC through bluetooth. There might be some slight sync issues that could be corrected but it sounds like this might be a reliable way to effectively replace a capture card?

**Comment by exelix11** [comment]
> Reading the new patch notes, it sounds like the low-latency streaming option is even faster than USB streaming

Not really, USB is the communication channel, low-latency is the streaming mode. The mode is a combination of player settings and more efficient data transfer protocols. You can stream in low-latency mode with both USB and network.

> because it can stream just a single channel for higher bandwidth 

Bandwidth is not the problem, it could be but there's a bigger problem first: the system service that provides gameplay recording is just slower at providing audio for whatever reason, not sure if this can ever be fixed on the SysDVR side.
You can see this if you enable low-latency RTSP the GUI for both streams, it will have almost a sec of delay because the player has to synchronize video and audio, but the stream doesn't lag, this means bandwidth is fine it's just audio being produced late.

Audio via bluetooth using the same capture method of SysDVR would have the same problem , the solution would be a sysmodule that hooks into the audio subsystem and sends it via bluetooth but that is outside the scope of this project.

Currently the best solution would be getting an audio capture card which should be cheap enough -cheaper than an actual capture card at least- or a crossup audio cable so you can record from the switch audio jack to your pc microphone, it would be mono only though.

> this might be a reliable way to effectively replace a capture card?

Guess so, there's still the issue that not all games are compatible but i'm looking into that.
