### ISSUE TITLE
there's a lot of delay mpv USB only (--cache=no --cache-secs=0)

### ISSUE THREAD

**Issue by Vegeta780** [exelix11/SysDVR#80]
**Setup information**
 - PC OS: [Windows 10 x64]
 - Console firmware [. 10.0.0]
 - Custom firmware name and version [. Atmosphere 0.12.0]
 - SysDVR version [e.g. 4.0.1 Usb-Only]

Hi am playing paper mario , problem is delaying video
mpv --cache=no --cache-secs=0 rtsp://127.0.0.1:6666/ 
i tried ffplay rtsp://127.0.0.1:6666/  and vlc palyer too all the 
still a lot of delay action of mario can you help me thanks

**Comment by Vegeta780** [comment]
Thanks a lot 
enabling Force LibUsb backend
and --profile=low-latency --no-cache --cache-secs=0 --demuxer-readahead-secs=0 --cache-pause=no working fine but sometimes screen freeze for one sec

**Comment by exelix11** [comment]
Hard to say, the fact you're using Force LibUsb backend means the driver is in fact not WinUsb but the other one so that may need to be sorted out.

Guess you could enable debug mode to print info on transfers if you can debug it but i can't really help you there, usual culprits are bad usb wires and driver misconfiguration.

Oh also you could try `--untimed` as well for mpv but that may cause desync.

**Comment by Vegeta780** [comment]
Thanks a lot now all problems is gone 
i disable  Force LibUsb backend and add --untimed option now no more freezing screen and working  awesome Thanks for your all hard work
