### ISSUE TITLE
[Feature request] Switch settings app to Tesla Overlay

### ISSUE THREAD

**Issue by benwa** [exelix11/SysDVR#87]
**Is your feature request related to a problem? Please describe.**
The simplicity of the settings app would work well as a [Tesla Overlay](/WerWolv/libtesla)

**Describe the solution you'd like**
Migrate the .nro to a .ovl for use with Tesla. A template repo is [here](/WerWolv/Tesla-Template)

**Comment by exelix11** [comment]
This is definitely possible but i don't use tesla so i'm not interested in doing it myself (and don't want to force other users into using it by not providing a simple nro settings app).
Right now i'm rewriting the settings protocol to be simpler and use native IPC instead of socket communication, it will have a libnx-like service wrapper lib for ease of integration so i guess i'll leave this one to the community.
