### ISSUE TITLE
Error trying to start stream

### ISSUE THREAD

**Issue by tomlube** [exelix11/SysDVR#97]
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName)
   at SysDVR.Client.Program.Main(String[] args)

**Comment by exelix11** [comment]
Windows version ? This error message usually means that you're trying to load a 64-bit dll from a 32-bit version of windows.
Now not sure why you get it with sdl, iirc i added the 32-bit build of that as well, maybe i mixed up the files (?).
Anyway if your PC is really 32-bit due to ffmpeg not providing 32-bit builds anymore the SysDVR-Client built-in player will not work unless you find the right dlls on your own from unofficial sources, either upgrade your pc or use mpv like previous versions.
You can check the edition of windows in your pc info.

**Comment by tomlube** [comment]
It's definitely 64 bit, that's bizarre

**Comment by exelix11** [comment]
Most likely you installed 32-bit net core, i've been debugging this specific error with another person yesterday. I've made a test app that prints the architecture of the ,net runtime you're running, try it: Extract [this](https://cdn.discordapp.com/attachments/643455945854156831/779104367474638888/bittest.7z) in a folder, open a cmd in there and run `dotnet bittest.dll`. If it prints running as 32.bit then you installed the wrong .NET (or both as depending on the order one may take priority). 
Uninstall 32-bit .NET and install the x64 one.

**Comment by exelix11** [comment]
[Latest release](https://github.com/exelix11/SysDVR/releases/latest) will show a warning when running as an x86 app.
